#pragma once

// Exact order from the legacy Tomodachi Life Save Editor (US Version)
// This matches the 231-byte block starting at 0x17F0 in the save file.
const int FOOD_COUNT = 231;
const char* FOOD_NAMES[] = {
    "Ice-cream cone",
    "Green juice",
    "Apple pie",
    "Strawberry",
    "Shashimi",
    "Orange juice",
    "Chocolate gâteau",
    "Crab",
    "Moldy bread",
    "Chewing gum",
    "Fried chicken",
    "Quiche",
    "Mushroom",
    "Kimchi",
    "Caviar",
    "Milk",
    "Pot stickers",
    "Spoiled milk",
    "Butter cookie",
    "Gummy candy",
    "Gratin",
    "Creamy stew",
    "Crepe",
    "Grapefuit",
    "Croissant",
    "Tea",
    "Coffee",
    "Tomato soup",
    "Rice",
    "Cherries",
    "Salad",
    "Sandwich",
    "Buttered potato",
    "Cream puff",
    "Strawberry shortcake",
    "White bread",
    "Watermelon",
    "Tap water",
    "Sushi",
    "Steak",
    "Sweet-and-sour pork",
    "Sausage",
    "Soft serve ice cream",
    "Tacos",
    "Fried Rice",
    "Chocolate",
    "Chocolate sundae",
    "Tempura",
    "Red chilli pepper",
    "Corn on the cob",
    "Doughnut",
    "Pork bun",
    "Banana",
    "Banana peel",
    "Fried spring rolls",
    "Cheeseburger",
    "Salisbury steak",
    "Pizza",
    "Cracker",
    "Grapes",
    "French fries",
    "Flan",
    "Blue cheese",
    "French toast",
    "Lollipop",
    "Patato chips",
    "Drumstick",
    "Macadamia nuts",
    "Spaghetti",
    "Orange",
    "Fried egg",
    "Peach",
    "Yakisoba",
    "Cooked eggplant",
    "Hard-boiled egg",
    "Ramen",
    "Apple",
    "Meat and patato stew",
    "Tomato juice",
    "Avocado",
    "Bacon",
    "Broccoli",
    "Calamari",
    "Roasted chestnuts",
    "Cotton candy",
    "Cappuccino",
    "Coconut",
    "Corn flakes",
    "Birthday cake",
    "Cheesecake",
    "Kiwi",
    "Lasagna",
    "Macaron",
    "Meatballs",
    "Melon",
    "Napoleon cake",
    "Muffin",
    "Raw oyster",
    "Paella",
    "Space food",
    "Peanuts",
    "Pear",
    "Pretzel",
    "Risotto",
    "Roast beef",
    "Salami",
    "Escargot",
    "Spaghetti peperoncino",
    "Squid-ink spaghetti",
    "Tiramisu",
    "Candy apple",
    "Truffle",
    "Roast turkey",
    "Waffle",
    "Yogurt",
    "Gelatin snack",
    "Soda",
    "Pancakes",
    "Instant noodles",
    "Popcorn",
    "Durian",
    "Garlic", "Stuffed cabbage roll", "Protein shake", "Tomato", "Apple juice", "Mango", "Hot dog", "Cheese", "Prosciutto", "Pineapple", "Salmon meuniere", "Chilli prawns", "Peking duck", "Octopus", "Green pepper", "Stewed beef", "Pot-au-feu", "Ruined meal", "Yakitori", "Fresh spring rolls", "Onion gratin soup", "Celery", "Smoothie", "Expresso", "Honey", "Gyro", "Lemonade", "Olives", "Polenta", "Ravioli", "Schnitzel", "Roast chicken", "Spanish omelet", "Biscuit", "Smoked salmon", "Sunflower seeds", "Chamomile tea", "Hot chocolate", "Black Forest gateau", "Prawn salad", "Pork cutlet", "Herring", "Liquorice", "Mashed potato", "Pasta pesto", "Danish pastry", "Porridge", "Beef jerky", "Brownie", "Carrot cake", "Chicken noodle soup", "Cinnamon roll", "Clam chowder", "Coleslaw", "Corn dog", "Eggnog", "Grits", "Hash browns", "Nachos", "Oatmeal", "Onion rings", "PB&J", "Pumpkin pie", "Split-pea soup", "Baked beans", "Baked potato", "Banana split", "Buble tea", "Buffalo wings", "Sardines", "Cherry pie", "Chicken pot pie", "Elephant ear", "Frozen yogurt", "Granola parfait", "Grilled cheese", "Hard candy", "Ice-cream sandwich", "Key lime pie", "Macaroni and cheese", "Milkshake", "Oatmeal cookie", "Red velvet cake", "S'more", "Spiced apple cider", "Stuffing", "Veggie burger", "Yerba maté", "Root-beer float", "String cheese", "Brussels sprouts", "Clotted cream", "Gingerbread cake", "Panini", "Fudge", "Fish cakes", "Fish sticks", "Loco moco", "Habanero", "Lobster", "Pickles", "Sports drink", "Popcorn shrimp", "Frozen treat", "Fried tofu", "Saltine crackers", "Filet mignon", "Fancy cupcake", "Barbecue", "Candy corn"
};
