#pragma once

// Extracted from the VB.NET Tomodachi Life Save Editor (US version)
// These are in EXACT save file order: item ID 0 = FOOD_NAMES[0], etc.
// Save offset: 0x17F0 + itemID, one byte per item (quantity 0-99)

const int FOOD_COUNT = 231;
const char* FOOD_NAMES[] = {
    "Ice-Cream Cone",
    "Green Juice",
    "Apple Pie",
    "Strawberry",
    "Sashimi",
    "Orange Juice",
    "Chocolate Gateau",
    "Crab",
    "Moldy Bread",
    "Chewing Gum",
    "Fried Chicken",
    "Quiche",
    "Mushroom",
    "Kimchi",
    "Caviar",
    "Milk",
    "Pot Stickers",
    "Spoiled Milk",
    "Butter Cookie",
    "Gummy Candy",
    "Gratin",
    "Creamy Stew",
    "Crepe",
    "Grapefruit",
    "Croissant",
    "Tea",
    "Coffee",
    "Tomato Soup",
    "Rice",
    "Cherries",
    "Salad",
    "Sandwich",
    "Buttered Potato",
    "Cream Puff",
    "Strawberry Shortcake",
    "White Bread",
    "Watermelon",
    "Tap Water",
    "Steak",
    "Sweet And Sour Pork",
    "Sausage",
    "Soft Serve Ice Cream",
    "Tacos",
    "Fried Rice",
    "Chocolate",
    "Chocolate Sundae",
    "Tempura",
    "Red Chilli Pepper",
    "Corn On The Cob",
    "Doughnut",
    "Pork Bun",
    "Banana",
    "Banana Peel",
    "Fried Spring Rolls",
    "Cheeseburger",
    "Salisbury Steak",
    "Pizza",
    "Cracker",
    "Grapes",
    "French Fries",
    "Flan",
    "Blue Cheese",
    "French Toast",
    "Lollipop",
    "Potato Chips",
    "Drumstick",
    "Macadamia Nuts",
    "Spaghetti",
    "Orange",
    "Fried Egg",
    "Peach",
    "Yakisoba",
    "Cooked Eggplant",
    "Hard-Boiled Egg",
    "Ramen",
    "Apple",
    "Meat And Potato Stew",
    "Tomato Juice",
    "Avocado",
    "Bacon",
    "Broccoli",
    "Calamari",
    "Roasted Chestnuts",
    "Cotton Candy",
    "Cappuccino",
    "Coconut",
    "Corn Flakes",
    "Birthday Cake",
    "Cheesecake",
    "Kiwi",
    "Lasagna",
    "Macaron",
    "Meatballs",
    "Melon",
    "Napoleon Cake",
    "Muffin",
    "Raw Oyster",
    "Paella",
    "Space Food",
    "Peanuts",
    "Pear",
    "Pretzel",
    "Risotto",
    "Roast Beef",
    "Salami",
    "Escargot",
    "Spaghetti Peperoncino",
    "Squid Ink Spaghetti",
    "Tiramisu",
    "Candy Apple",
    "Truffle",
    "Roast Turkey",
    "Waffle",
    "Yogurt",
    "Gelatin Snack",
    "Soda",
    "Pancakes",
    "Instant Noodles",
    "Popcorn",
    "Durian",
    "Garlic",
    "Stuffed Cabbage Roll",
    "Protein Shake",
    "Tomato",
    "Apple Juice",
    "Mango",
    "Hot Dog",
    "Cheese",
    "Prosciutto",
    "Pineapple",
    "Salmon Meuniere",
    "Chilli Prawns",
    "Peking Duck",
    "Octopus",
    "Green Pepper",
    "Stewed Beef",
    "Pot-Au-Feu",
    "Ruined Meal",
    "Yakitori",
    "Fresh Spring Rolls",
    "Onion Gratin Soup",
    "Celery",
    "Smoothie",
    "Espresso",
    "Honey",
    "Gyro",
    "Lemonade",
    "Olives",
    "Polenta",
    "Ravioli",
    "Schnitzel",
    "Roast Chicken",
    "Spanish Omelet",
    "Biscuit",
    "Smoked Salmon",
    "Sunflower Seeds",
    "Chamomile Tea",
    "Hot Chocolate",
    "Black Forest Gateau",
    "Prawn Salad",
    "Pork Cutlet",
    "Herring",
    "Licorice",
    "Mashed Potato",
    "Pasta Pesto",
    "Danish Pastry",
    "Porridge",
    "Beef Jerky",
    "Brownie",
    "Carrot Cake",
    "Chicken Noodle Soup",
    "Cinnamon Roll",
    "Clam Chowder",
    "Coleslaw",
    "Corn Dog",
    "Eggnog",
    "Grits",
    "Hash Browns",
    "Nachos",
    "Oatmeal",
    "Onion Rings",
    "PB&J",
    "Pumpkin Pie",
    "Split-Pea Soup",
    "Baked Beans",
    "Baked Potato",
    "Banana Split",
    "Bubble Tea",
    "Buffalo Wings",
    "Sardines",
    "Cherry Pie",
    "Chicken Pot Pie",
    "Elephant Ear",
    "Frozen Yogurt",
    "Granola Parfait",
    "Grilled Cheese",
    "Hard Candy",
    "Ice-Cream Sandwich",
    "Key Lime Pie",
    "Macaroni And Cheese",
    "Milkshake",
    "Oatmeal Cookie",
    "Red Velvet Cake",
    "S'more",
    "Spiced Apple Cider",
    "Stuffing",
    "Veggie Burger",
    "Yerba Mate",
    "Root-Beer Float",
    "String Cheese",
    "Brussels Sprouts",
    "Clotted Cream",
    "Gingerbread Cake",
    "Panini",
    "Fudge",
    "Fishcakes",
    "Fish Sticks",
    "Loco Moco",
    "Habanero",
    "Lobster",
    "Pickles",
    "Sports Drink",
    "Popcorn Shrimp",
    "Frozen Treat",
    "Fried Tofu",
    "Saltine Crackers",
    "Filet Mignon",
    "Fancy Cupcake",
    "Barbecue",
    "Candy Corn",
    "Sushi"
};
